### ISSUE TITLE
Failed to run dev

### ISSUE THREAD

**Issue by EgyptianM** [freqtrade/frequi#1950]
**FreqUI Version**

- Version of freqUI: 1.3.1
- version of freqtrade: 2024.5

**Describe the bug**
When I tried to run `pnpm run dev` I got this exception :

```
mohammad@mohammad-TravelMate-P253:~/Downloads/frequi-1.3.1$ pnpm run dev

> frequi@0.1.0 dev /home/mohammad/Downloads/frequi-1.3.1
> vite

fatal: Needed a single revision
failed to load config from /home/mohammad/Downloads/frequi-1.3.1/vite.config.ts
error when starting dev server:
Error: Command failed: git rev-parse --short HEAD
fatal: Needed a single revision

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at file:///home/mohammad/Downloads/frequi-1.3.1/vite.config.ts.timestamp-1719663462786-fd56967de4306.mjs:12:18
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadConfigFromBundledFile (file:///home/mohammad/Downloads/frequi-1.3.1/node_modules/.pnpm/vite@5.2.12_@types+node@20.12.12_sass@1.77.2/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:69911:21)
    at async loadConfigFromFile (file:///home/mohammad/Downloads/frequi-1.3.1/node_modules/.pnpm/vite@5.2.12_@types+node@20.12.12_sass@1.77.2/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:69764:28)
    at async resolveConfig (file:///home/mohammad/Downloads/frequi-1.3.1/node_modules/.pnpm/vite@5.2.12_@types+node@20.12.12_sass@1.77.2/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:69367:28)
 ELIFECYCLE  Command failed with exit code 1.
```

Same error with the last release and last code available on Github

**To Reproduce**

1. Download the code from Github
2. run `pnpm install`
3. run `pnpm run dev`

**Desktop (please complete the following information):**
 - OS: Linux Mint 21
 - Browser Firefox
 - Version 127.0.2 (64-bit)

**Comment by xmatthias** [comment]
Well from the error, it doesn't look like your "download" is a regular git clone.


For develop mode (run dev), thats not something we are going to support.

If you intend to run dev mode, use a git cloned directory instead.
