### ISSUE TITLE
i got error when i want run backend script

### ISSUE THREAD

**Issue by vahidarjmand** [freqtrade/frequi#363]
* Operating system: win10
  * Python Version: 3.8.8
  * CCXT version: 1.50.48
  * Freqtrade Version: 2021.5
  
when i want to run  this command for run backend script 

`python scripts/rest_client.py --config scripts/rest_config.json start`

i got this error

``` Traceback (most recent call last):
  File "scripts/rest_client.py", line 419, in <module>
    main(args)
  File "scripts/rest_client.py", line 414, in main
    print(json.dumps(getattr(client, command)(*args["command_arguments"])))
  File "scripts/rest_client.py", line 77, in start
    return self._post("start")
  File "scripts/rest_client.py", line 70, in _post
    return self._call("POST", apipath, params=params, data=data)
  File "scripts/rest_client.py", line 59, in _call
    return resp.json()
  File "H:\bot\freqtrade\.env\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\tmedia\anaconda3\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\tmedia\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\tmedia\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```
 how can i solve this problem ?

**Comment by xmatthias** [comment]
are you sure that the bot is already running?

the API is only available when the bot is running in `freqtrade trade` mode.

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered.

Feel free to comment below / reopen if it's still unclear.
